services:
  postgres:
    image: postgres:15
    container_name: postgres_ed
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build: .
    environment:
      SOURCE_DB_HOST: ${SOURCE_DB_HOST}
      SOURCE_DB_PORT: ${SOURCE_DB_PORT}
      SOURCE_DB_NAME: ${SOURCE_DB_NAME}
      SOURCE_DB_USER: ${SOURCE_DB_USER}
      SOURCE_DB_PASSWORD: ${SOURCE_DB_PASSWORD}
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    tty: true

volumes:
  postgres_data: